// Build: bundles src/ (Three.js + addons) into one classic script so index.html works via file://
// Usage: node tools/build.mjs   (needs three + esbuild in ../grok-bot-chess-build/node_modules or NODE_PATH)
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(resolve(root, '../grok-bot-chess-build/package.json'));
const { build } = require('esbuild');
const nodePaths = [resolve(root, '../grok-bot-chess-build/node_modules'), ...(process.env.NODE_PATH || '').split(':').filter(Boolean)];

await build({
  entryPoints: [resolve(root, 'src/entry.js')],
  bundle: true,
  format: 'iife',
  minify: true,
  target: ['es2020', 'safari15'],
  outfile: resolve(root, 'js/app3d.bundle.js'),
  nodePaths,
  legalComments: 'eof',
  banner: { js: '/* Grok Bot Chess 3D — bundled with three.js (MIT, (c) 2010-2026 three.js authors) */' }
});

// Inline the AI worker source (engine + AI + message handler) as a string,
// so a Blob-based Web Worker can be created even from file://
const engine = readFileSync(resolve(root, 'js/chess-engine.js'), 'utf8');
const ai = readFileSync(resolve(root, 'js/ai.js'), 'utf8');
const handler = `
self.onmessage = function (e) {
  var d = e.data || {};
  var mv = null;
  try { mv = self.GardenAI.chooseMoveLevel(d.state, d.level || 2); } catch (err) { mv = null; }
  self.postMessage({ id: d.id, move: mv });
};`;
const src = engine + '\n' + ai + '\n' + handler;
writeFileSync(resolve(root, 'js/ai-worker-src.js'), '/* generated by tools/build.mjs */\nwindow.GBC_WORKER_SRC = ' + JSON.stringify(src) + ';\n');

// Stockfish 19 lite (single-threaded WASM, GPLv3) → one classic script with the wasm embedded as base64.
// The worker runs from a Blob URL; a tiny prelude answers the engine's wasm fetch from memory, so it works from file://.
const sfDir = resolve(root, '../grok-bot-chess-build/node_modules/stockfish/bin');
if (existsSync(resolve(sfDir, 'stockfish-19-lite-single.wasm'))) {
  const sfJs = readFileSync(resolve(sfDir, 'stockfish-19-lite-single.js'), 'utf8');
  const b64 = readFileSync(resolve(sfDir, 'stockfish-19-lite-single.wasm')).toString('base64');
  const prelude = `/* Grok Bot Chess: embedded wasm loader (wasm = stockfish-19-lite-single.wasm, GPLv3) */
(function(){var b=atob(${JSON.stringify(b64)}),n=b.length,u=new Uint8Array(n);for(var i=0;i<n;i++)u[i]=b.charCodeAt(i);
self.fetch=function(){return Promise.resolve(new Response(new Blob([u],{type:'application/wasm'}),{status:200,headers:{'Content-Type':'application/wasm'}}));};})();
`;
  writeFileSync(resolve(root, 'js/stockfish-src.js'), '/* generated by tools/build.mjs – Stockfish.js 19 lite (c) Chess.com, LLC / Stockfish developers, GPLv3, source: https://github.com/nmrugg/stockfish.js */\nwindow.GBC_SF_SRC = ' + JSON.stringify(prelude + sfJs) + ';\n');
  mkdirSync(resolve(root, 'LICENSES'), { recursive: true });
  copyFileSync(resolve(sfDir, '../Copying.txt'), resolve(root, 'LICENSES/Stockfish-GPL-3.0.txt'));
  console.log('built js/stockfish-src.js (' + Math.round(b64.length / 1024) + ' KB wasm b64)');
}
console.log('built js/app3d.bundle.js + js/ai-worker-src.js');
